name 'chef-client'
maintainer 'Mike Butler'
maintainer_email 'michael.butler@chef.io'
license 'All Rights Reserved'
description 'Installs/Configures chef-client'
version '1.3.2'
chef_version '>= 17.0'
