---
  on:
    pull_request:
  
  jobs:
    markdownlint:
      uses: snohio/github-workflows/.github/workflows/markdown-lint.yml@main
  
    yamllint:
      uses: snohio/github-workflows/.github/workflows/yaml-lint.yml@main
  
    jsonlint:
      uses: snohio/github-workflows/.github/workflows/json-lint.yml@main
  
    cookstylelint:
      uses: snohio/github-workflows/.github/workflows/cookstyle-lint.yml@main
  
    integration-azure:
      runs-on: ubuntu-latest
      needs:
        - markdownlint
        - yamllint
        - jsonlint
        - cookstylelint
      strategy:
        matrix:
          os:
            - ubuntu-18
            - ubuntu-20
            - ubuntu-22
            - RHEL7
            - RHEL8
            - Windows2019
            - Windows2022
            - Windows-10
            - Windows-11
          suite:
            - default
        fail-fast: false
      steps:
        - name: Check out code
          uses: actions/checkout@main
        - name: Install Chef
          uses: actionshub/chef-install@main
        - name: Azure Credentials
          run: | 
            mkdir ~/.azure
            cat > ~/.azure/credentials << EOF
            [${{ secrets.SUBSCRIPTION_ID }}]
            client_id = "${{ secrets.CLIENT_ID }}"
            client_secret = "${{ secrets.CLIENT_SECRET }}"
            tenant_id = "${{ secrets.TENANT_ID }}"
            EOF
        - name: Test-Kitchen Converge
          uses: actionshub/test-kitchen@main
          with:
            suite: ${{ matrix.suite }}
            os: ${{ matrix.os }}
            action: converge
          env:
            CHEF_LICENSE: accept-no-persist
            KITCHEN_LOCAL_YAML: kitchen.azure.yml
            AZURE_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
            AZURE_TAGS: ${{ vars.AZURE_TAGS }}
        - name: Test-Kitchen Verify
          uses: actionshub/test-kitchen@main
          with:
            suite: ${{ matrix.suite }}
            os: ${{ matrix.os }}
            action: verify
          env:
            CHEF_LICENSE: accept-no-persist
            KITCHEN_LOCAL_YAML: kitchen.azure.yml
            AZURE_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        - name: Test-Kitchen Destroy
          if: always()
          uses: actionshub/test-kitchen@main
          with:
            suite: ${{ matrix.suite }}
            os: ${{ matrix.os }}
            action: destroy
          env:
            CHEF_LICENSE: accept-no-persist
            KITCHEN_LOCAL_YAML: kitchen.azure.yml
            AZURE_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
    integration-macos:
      runs-on: macos-latest
      needs:
        - markdownlint
        - yamllint
        - jsonlint
        - cookstylelint
      strategy:
        matrix:
          os:
            - macos-latest
          suite:
            - default
        fail-fast: false
      steps:
        - name: Check out code
          uses: actions/checkout@main
        - name: Install Chef
          uses: actionshub/chef-install@main
        - name: Test-Kitchen Converge
          uses: actionshub/test-kitchen@main
          with:
            suite: ${{ matrix.suite }}
            os: ${{ matrix.os }}
            action: converge
          env:
            CHEF_LICENSE: accept-no-persist
            KITCHEN_LOCAL_YAML: kitchen.exec.yml
        - name: Test-Kitchen Verify
          uses: actionshub/test-kitchen@main
          with:
            suite: ${{ matrix.suite }}
            os: ${{ matrix.os }}
            action: verify
          env:
            CHEF_LICENSE: accept-no-persist
            KITCHEN_LOCAL_YAML: kitchen.exec.yml
    check:
      if: always()
      needs:
        - markdownlint
        - yamllint
        - jsonlint
        - cookstylelint
        - integration-azure
  
      runs-on: ubuntu-latest
      steps:
        - name: Decide whether the needed jobs succeeded or failed
          uses: re-actors/alls-green@main
          with:
            allowed-failures: 
            allowed-skips: 
            jobs: ${{ toJSON(needs) }}
  